version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=8991
      - DB=db_gamer_shop
      - DB_USER=gabriel
      - SECRET_KEY=7792125bbce085d0b54cd64a7065aef4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=8991
      - POSTGRES_DB=db_gamer_shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabriel -d db_gamer_shop"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_db_gamer_shop:/var/lib/postgresql/data

volumes:
  postgres_db_gamer_shop:
    driver: local