version: '3.9'

services:
  api:
    container_name: api_gamer_shop
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db_shop
      - DB_PASSWORD=8991
      - DB=db_gamer_shop
      - DB_USER=gabriel
      - SECRET_KEY=jdisjadisajdopasjop342
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db_shop
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=8991
      - POSTGRES_DB=db_gamer_shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabriel -d db_gamer_shop"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_gamer_shop:/var/lib/postgresql/data

volumes:
  postgres_gamer_shop:
    driver: local